{
  stdenv,
  fetchgit,
  ...
}:

let
  version = import ./version.nix; # generated by ./update.sh
in
  stdenv.mkDerivation {
    pname = "sf-mono-nerd-font";
    inherit version;
    src = fetchgit {
      url = "https://github.com/epk/SF-Mono-Nerd-Font";
      rev = "${version}";
      sha256 = "sha256-f5A/vTKCUxdMhCqv0/ikF46tRrx5yZfIkvfExb3/XEQ=";
    };
    installPhase = ''
      mkdir -p $out/share/fonts/opentype
      mv *.otf $out/share/fonts/opentype
    '';

    meta = {
      description = "Apple's SF Mono font patched with the Nerd Fonts patcher";
    };
  }
